// <auto-generated />
using System;
using Emc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emc.Infrastructure.Migrations
{
    [DbContext(typeof(EmcDbContext))]
    [Migration("20260904013250_AppendOnlyTriggers")]
    partial class AppendOnlyTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emc.Domain.Cases.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseControlNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClassificationMarking")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId", "CaseControlNumber")
                        .IsUnique();

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountabilityStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyDenominationBreakdown")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("CurrencyTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsCurrency")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFungible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPossibleBiohazard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastEventHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("LastEventSequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SealDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UniqueDeviceIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("VoucherId", "ItemNumber")
                        .IsUnique();

                    b.ToTable("EvidenceItems", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AcquiredAtLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("AcquiredAtOffset")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequestForAssistance")
                        .HasColumnType("bit");

                    b.Property<int>("PreparedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReceivedFrom")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReceivingActivity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReceivingActivityLocation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RequestingOfficeCaseNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ReviewStage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("TemporaryIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EvidenceRoomId", "TemporaryIdentifier")
                        .IsUnique();

                    b.ToTable("EvidenceVouchers", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.OfficialDocumentNumberAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AttestedAssignedInAuthoritativeLedger")
                        .HasColumnType("bit");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("EnteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EnteredByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberingPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("SupersedesAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("SupersessionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumberingPolicyId");

                    b.HasIndex("SupersedesAssignmentId");

                    b.HasIndex("VoucherId");

                    b.HasIndex("EvidenceRoomId", "CalendarYear", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_DocumentNumber_NeverReusedPerRoomPerYear");

                    b.ToTable("OfficialDocumentNumberAssignments", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.TemporaryIdentifierCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<int>("LastOrdinal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId", "Date")
                        .IsUnique();

                    b.ToTable("TemporaryIdentifierCounters", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.VoucherFormRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("VoucherFormRevisions", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.VoucherFormRevisionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("EvidenceItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPossibleBiohazard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RevisionId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UniqueDeviceIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceItemId");

                    b.HasIndex("RevisionId", "LineNumber")
                        .IsUnique();

                    b.ToTable("VoucherFormRevisionLines", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.VoucherReviewAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Narrative")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("PaperFormCorrectedAndInitialedAttested")
                        .HasColumnType("bit");

                    b.Property<int>("ResultingStage")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("VoucherId", "OccurredAtUtc");

                    b.ToTable("VoucherReviewActions", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Configuration.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActingUserId")
                        .HasColumnType("int");

                    b.Property<string>("ActingUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AffectedRecordId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AffectedRecordType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ActingUserId", "OccurredAtUtc");

                    b.HasIndex("AffectedRecordType", "AffectedRecordId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Configuration.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccreditedClassificationLevel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AuthoritativeMode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AutomatedSystemApprovalDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AutomatedSystemApprovalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LocalSuspenseReviewThresholdDays")
                        .HasColumnType("int");

                    b.Property<int>("NumberingMode")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Documents.DocumentRenderJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LastFailureCategory")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LeasedByWorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("DocumentRenderJobs", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Documents.DocumentRenderPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("RenderRunId")
                        .HasColumnType("int");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("RenderRunId", "PageNumber")
                        .IsUnique();

                    b.ToTable("DocumentRenderPages", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Documents.DocumentRenderRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailureCategory")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("RenderDpi")
                        .HasColumnType("int");

                    b.Property<int>("RenderJobId")
                        .HasColumnType("int");

                    b.Property<string>("RendererVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("RenderJobId");

                    b.HasIndex("SourceDocumentId", "Outcome", "CompletedAtUtc");

                    b.ToTable("DocumentRenderRuns", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Documents.SourceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("ClassificationMarking")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("Provenance")
                        .HasColumnType("int");

                    b.Property<string>("ProvenanceNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("VoucherId");

                    b.HasIndex("EvidenceRoomId", "Sha256");

                    b.ToTable("SourceDocuments", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountableMailNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IdentificationVerified")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationOrAgency")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleOrGrade")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustodyParties", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Events.ItemEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("EvidenceItemId")
                        .HasColumnType("int");

                    b.Property<int>("HashSchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("OccurredAtLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("OccurredAtOffset")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreviousEventHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SourceDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceItemId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ItemEvents_ItemSequence");

                    b.HasIndex("EvidenceItemId", "OccurredAtUtc", "SequenceNumber")
                        .HasDatabaseName("IX_ItemEvents_ItemChronology");

                    b.ToTable("ItemEvents", (string)null);

                    b.HasDiscriminator<string>("EventKind").HasValue("ItemEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Emc.Domain.Filing.PhysicalFileContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DispositionMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DispositionYear")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumberRangeFrom")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("DocumentNumberRangeTo")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<int>("FiledVoucherCount")
                        .HasColumnType("int");

                    b.Property<int>("Form")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("RangeCalendarYear")
                        .HasColumnType("int");

                    b.Property<int?>("RangeFromSequence")
                        .HasColumnType("int");

                    b.Property<int?>("RangeToSequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId", "Kind", "Label")
                        .IsUnique();

                    b.HasIndex("EvidenceRoomId", "RangeCalendarYear", "RangeFromSequence");

                    b.ToTable("PhysicalFileContainers", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Filing.PhysicalVoucherDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CopyReason")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentContainerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DestructionConfirmedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DestructionConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeActiveContainerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("InactiveSinceUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OriginalDisposition")
                        .HasColumnType("int");

                    b.Property<int>("RetainedPaperStatus")
                        .HasColumnType("int");

                    b.Property<bool>("SuspenseCopyFiledWithOriginal")
                        .HasColumnType("bit");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentContainerId");

                    b.HasIndex("EvidenceRoomId");

                    b.HasIndex("HomeActiveContainerId");

                    b.HasIndex("VoucherId")
                        .IsUnique();

                    b.ToTable("PhysicalVoucherDocuments", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Filing.PhysicalVoucherDocumentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContainerId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Narrative")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ResultingOriginalDisposition")
                        .HasColumnType("int");

                    b.Property<int>("ResultingRetainedPaperStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("DocumentId", "OccurredAtUtc");

                    b.ToTable("PhysicalVoucherDocumentEvents", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.CustodianAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppointingAuthority")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AppointmentOrderReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EligibilityAttested")
                        .HasColumnType("bit");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PersonnelCategory")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SupersededByAppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("SupersedesAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EvidenceRoomId", "AppointmentType")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodianAppointments_OneOpenPerType")
                        .HasFilter("EffectiveTo IS NULL AND SupersededByAppointmentId IS NULL");

                    b.HasIndex("EvidenceRoomId", "UserId", "EffectiveFrom");

                    b.ToTable("CustodianAppointments", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.CustodianDutyAssumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlternateAppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AlternateAssumedDutiesAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AlternateUserId")
                        .HasColumnType("int");

                    b.Property<string>("AssumptionLedgerAttestation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpectedAbsenceEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PrimaryAbsenceStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PrimaryAppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PrimaryResumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReasonForAbsence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResumptionLedgerAttestation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("ResumptionRecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ResumptionRecordedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateAppointmentId");

                    b.HasIndex("EvidenceRoomId")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodianDutyAssumptions_OneOpenPerRoom")
                        .HasFilter("PrimaryResumedAt IS NULL");

                    b.HasIndex("PrimaryAppointmentId");

                    b.HasIndex("AlternateUserId", "EvidenceRoomId");

                    b.ToTable("CustodianDutyAssumptions", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.PrimaryCustodianTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DiscrepanciesResolved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<int>("IncomingPrimaryAppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("JointInventoryCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JointInventoryReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LedgerAttestation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("OutgoingPrimaryAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncomingPrimaryAppointmentId");

                    b.HasIndex("OutgoingPrimaryAppointmentId");

                    b.HasIndex("EvidenceRoomId", "EffectiveFrom");

                    b.ToTable("PrimaryCustodianTransitions", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.RoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "EvidenceRoomId");

                    b.HasIndex("UserId", "RoleId", "EvidenceRoomId")
                        .IsUnique()
                        .HasDatabaseName("UX_RoleAssignments_OneOpenPerUserRoleRoom")
                        .HasFilter("EffectiveTo IS NULL");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDirectorySid")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("nvarchar(184)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationOrUnit")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RankOrGrade")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDirectorySid")
                        .IsUnique();

                    b.HasIndex("UserPrincipalName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Ocr.ExtractedField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Band")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsHighConsequence")
                        .HasColumnType("bit");

                    b.Property<int>("Left")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedCandidate")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("OcrRunId")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("RequiresVerification")
                        .HasColumnType("bit");

                    b.Property<int>("Top")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OcrRunId", "PageNumber");

                    b.ToTable("ExtractedFields", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Ocr.FieldVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("EnteredValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ExtractedFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("VerifiedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("ExtractedFieldId", "VerifiedAtUtc");

                    b.ToTable("FieldVerifications", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Ocr.OcrJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LastFailureCategory")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LeasedByWorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RenderRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId");

                    b.HasIndex("RenderRunId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("OcrJobs", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Ocr.OcrRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FailureCategory")
                        .HasColumnType("int");

                    b.Property<string>("ModelIdentifiers")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("OcrJobId")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("PagesProcessed")
                        .HasColumnType("int");

                    b.Property<string>("PreprocessingVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RenderRunId")
                        .HasColumnType("int");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("TemplateIdentified")
                        .HasColumnType("bit");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OcrJobId");

                    b.HasIndex("RenderRunId");

                    b.HasIndex("SourceDocumentId", "CompletedAtUtc");

                    b.ToTable("OcrRuns", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Ocr.OcrRunPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DeskewAppliedDegrees")
                        .HasColumnType("float");

                    b.Property<int>("Dpi")
                        .HasColumnType("int");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int");

                    b.Property<int>("OcrRunId")
                        .HasColumnType("int");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("RotationAppliedDegrees")
                        .HasColumnType("int");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("OcrRunId", "PageNumber")
                        .IsUnique();

                    b.ToTable("OcrRunPages", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Reconciliation.ReconciliationFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanionValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("DocumentValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EvidenceItemId")
                        .HasColumnType("int");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Narrative")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("OcrRunId")
                        .HasColumnType("int");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("EvidenceItemId");

                    b.HasIndex("OcrRunId");

                    b.HasIndex("VoucherId");

                    b.HasIndex("SourceDocumentId", "FieldKey");

                    b.ToTable("ReconciliationFindings", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Storage.EvidenceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrganizationOrUnit")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EvidenceRooms", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Storage.EvidenceRoomNumberingPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorityReference")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Basis")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Separator")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("SequenceWidth")
                        .HasColumnType("int");

                    b.Property<int>("YearWidth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId", "EffectiveFrom");

                    b.ToTable("EvidenceRoomNumberingPolicies", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Storage.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("EvidenceRoomId", "ParentId", "Name")
                        .IsUnique()
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Events.CorrectionEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CorrectedReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectedValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("CorrectsEventId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MfrReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OriginalReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("PreviousEffectiveReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousEffectiveValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ReferenceKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SupervisorNotifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SupervisorNotifiedGradeOrTitle")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SupervisorNotifiedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SupervisorNotifiedOrganization")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SupervisorNotifiedUserId")
                        .HasColumnType("int");

                    b.HasIndex("CorrectsEventId");

                    b.HasIndex("ReferenceKind", "CorrectedReferenceId")
                        .HasDatabaseName("IX_ItemEvents_CorrectionReference")
                        .HasFilter("[CorrectedReferenceId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Correction");
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<string>("Agency")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Destination")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsScrcni")
                        .HasColumnType("bit");

                    b.Property<string>("PurposeOfChangeOfCustody")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReceivedByPartyId")
                        .HasColumnType("int");

                    b.Property<int>("ReleasedByPartyId")
                        .HasColumnType("int");

                    b.HasIndex("ReceivedByPartyId");

                    b.HasIndex("ReleasedByPartyId");

                    b.HasDiscriminator().HasValue("Custody");
                });

            modelBuilder.Entity("Emc.Domain.Events.DocumentNumberEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<bool>("AttestedAssignedInAuthoritativeLedger")
                        .HasColumnType("bit");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PreviousDocumentNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasDiscriminator().HasValue("DocumentNumber");
                });

            modelBuilder.Entity("Emc.Domain.Events.ExaminationEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<string>("ExaminationRequestReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExhibitNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExtractionDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Laboratory")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResultReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasDiscriminator().HasValue("Examination");
                });

            modelBuilder.Entity("Emc.Domain.Events.LocationEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StorageLocationId")
                        .HasColumnType("int");

                    b.Property<string>("StorageLocationPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.ToTable("ItemEvents", t =>
                        {
                            t.Property("Reason")
                                .HasColumnName("LocationEvent_Reason");
                        });

                    b.HasDiscriminator().HasValue("Location");
                });

            modelBuilder.Entity("Emc.Domain.Events.SealEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("DirectingSupervisorName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MfrReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PurposeOfBreach")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.ToTable("ItemEvents", t =>
                        {
                            t.Property("MfrReference")
                                .HasColumnName("SealEvent_MfrReference");
                        });

                    b.HasDiscriminator().HasValue("Seal");
                });

            modelBuilder.Entity("Emc.Domain.Events.StatusEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.ToTable("ItemEvents", t =>
                        {
                            t.Property("Reason")
                                .HasColumnName("StatusEvent_Reason");
                        });

                    b.HasDiscriminator().HasValue("Status");
                });

            modelBuilder.Entity("Emc.Domain.Cases.Case", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceItem", b =>
                {
                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", "Voucher")
                        .WithMany("Items")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceVoucher", b =>
                {
                    b.HasOne("Emc.Domain.Cases.Case", "Case")
                        .WithMany("Vouchers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Emc.Domain.Cases.OfficialDocumentNumberAssignment", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Storage.EvidenceRoomNumberingPolicy", null)
                        .WithMany()
                        .HasForeignKey("NumberingPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emc.Domain.Cases.OfficialDocumentNumberAssignment", null)
                        .WithMany()
                        .HasForeignKey("SupersedesAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", "Voucher")
                        .WithMany("DocumentNumberAssignments")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Emc.Domain.Cases.TemporaryIdentifierCounter", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Cases.VoucherFormRevision", b =>
                {
                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", "Voucher")
                        .WithMany("FormRevisions")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Emc.Domain.Cases.VoucherFormRevisionLine", b =>
                {
                    b.HasOne("Emc.Domain.Cases.EvidenceItem", "EvidenceItem")
                        .WithMany()
                        .HasForeignKey("EvidenceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Cases.VoucherFormRevision", "Revision")
                        .WithMany("Lines")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvidenceItem");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Emc.Domain.Cases.VoucherReviewAction", b =>
                {
                    b.HasOne("Emc.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", "Voucher")
                        .WithMany("ReviewActions")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Emc.Domain.Documents.DocumentRenderJob", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Documents.SourceDocument", "Document")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Emc.Domain.Documents.DocumentRenderPage", b =>
                {
                    b.HasOne("Emc.Domain.Documents.DocumentRenderRun", "Run")
                        .WithMany("Pages")
                        .HasForeignKey("RenderRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Emc.Domain.Documents.DocumentRenderRun", b =>
                {
                    b.HasOne("Emc.Domain.Documents.DocumentRenderJob", null)
                        .WithMany()
                        .HasForeignKey("RenderJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Documents.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Documents.SourceDocument", b =>
                {
                    b.HasOne("Emc.Domain.Cases.Case", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyParty", b =>
                {
                    b.HasOne("Emc.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emc.Domain.Events.ItemEvent", b =>
                {
                    b.HasOne("Emc.Domain.Cases.EvidenceItem", null)
                        .WithMany("Events")
                        .HasForeignKey("EvidenceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Filing.PhysicalFileContainer", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", "EvidenceRoom")
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvidenceRoom");
                });

            modelBuilder.Entity("Emc.Domain.Filing.PhysicalVoucherDocument", b =>
                {
                    b.HasOne("Emc.Domain.Filing.PhysicalFileContainer", null)
                        .WithMany()
                        .HasForeignKey("CurrentContainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Filing.PhysicalFileContainer", null)
                        .WithMany()
                        .HasForeignKey("HomeActiveContainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Filing.PhysicalVoucherDocumentEvent", b =>
                {
                    b.HasOne("Emc.Domain.Filing.PhysicalVoucherDocument", "Document")
                        .WithMany("Events")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Emc.Domain.Identity.CustodianAppointment", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emc.Domain.Identity.CustodianDutyAssumption", b =>
                {
                    b.HasOne("Emc.Domain.Identity.CustodianAppointment", null)
                        .WithMany()
                        .HasForeignKey("AlternateAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.CustodianAppointment", null)
                        .WithMany()
                        .HasForeignKey("PrimaryAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Identity.PrimaryCustodianTransition", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.CustodianAppointment", null)
                        .WithMany()
                        .HasForeignKey("IncomingPrimaryAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.CustodianAppointment", null)
                        .WithMany()
                        .HasForeignKey("OutgoingPrimaryAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Emc.Domain.Identity.RoleAssignment", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emc.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emc.Domain.Ocr.ExtractedField", b =>
                {
                    b.HasOne("Emc.Domain.Ocr.OcrRun", "Run")
                        .WithMany("Fields")
                        .HasForeignKey("OcrRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Emc.Domain.Ocr.FieldVerification", b =>
                {
                    b.HasOne("Emc.Domain.Ocr.ExtractedField", "Field")
                        .WithMany("Verifications")
                        .HasForeignKey("ExtractedFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Emc.Domain.Ocr.OcrJob", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Documents.DocumentRenderRun", null)
                        .WithMany()
                        .HasForeignKey("RenderRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Documents.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Ocr.OcrRun", b =>
                {
                    b.HasOne("Emc.Domain.Ocr.OcrJob", null)
                        .WithMany()
                        .HasForeignKey("OcrJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Documents.DocumentRenderRun", null)
                        .WithMany()
                        .HasForeignKey("RenderRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Documents.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Ocr.OcrRunPage", b =>
                {
                    b.HasOne("Emc.Domain.Ocr.OcrRun", "Run")
                        .WithMany("Pages")
                        .HasForeignKey("OcrRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Emc.Domain.Reconciliation.ReconciliationFinding", b =>
                {
                    b.HasOne("Emc.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Cases.EvidenceItem", null)
                        .WithMany()
                        .HasForeignKey("EvidenceItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Emc.Domain.Ocr.OcrRun", null)
                        .WithMany()
                        .HasForeignKey("OcrRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Documents.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Storage.EvidenceRoomNumberingPolicy", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", "EvidenceRoom")
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvidenceRoom");
                });

            modelBuilder.Entity("Emc.Domain.Storage.StorageLocation", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", "EvidenceRoom")
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Storage.StorageLocation", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EvidenceRoom");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Emc.Domain.Events.CorrectionEvent", b =>
                {
                    b.HasOne("Emc.Domain.Events.ItemEvent", "CorrectedEvent")
                        .WithMany()
                        .HasForeignKey("CorrectsEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorrectedEvent");
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyEvent", b =>
                {
                    b.HasOne("Emc.Domain.Events.CustodyParty", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Events.CustodyParty", "ReleasedBy")
                        .WithMany()
                        .HasForeignKey("ReleasedByPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivedBy");

                    b.Navigation("ReleasedBy");
                });

            modelBuilder.Entity("Emc.Domain.Cases.Case", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceItem", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceVoucher", b =>
                {
                    b.Navigation("DocumentNumberAssignments");

                    b.Navigation("FormRevisions");

                    b.Navigation("Items");

                    b.Navigation("ReviewActions");
                });

            modelBuilder.Entity("Emc.Domain.Cases.VoucherFormRevision", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Emc.Domain.Documents.DocumentRenderRun", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("Emc.Domain.Filing.PhysicalVoucherDocument", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Emc.Domain.Ocr.ExtractedField", b =>
                {
                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Emc.Domain.Ocr.OcrRun", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
