// <auto-generated />
using System;
using Emc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emc.Infrastructure.Migrations
{
    [DbContext(typeof(EmcDbContext))]
    partial class EmcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emc.Domain.Cases.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseControlNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClassificationMarking")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceRoomId", "CaseControlNumber")
                        .IsUnique();

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountabilityStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyDenominationBreakdown")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("CurrencyTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsCurrency")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFungible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPossibleBiohazard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("int");

                    b.Property<int>("LastEventSequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SealDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UniqueDeviceIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("VoucherId", "ItemNumber")
                        .IsUnique();

                    b.ToTable("EvidenceItems", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AcquiredAtLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("AcquiredAtOffset")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequestForAssistance")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<int>("PreparedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReceivedFrom")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReceivingActivity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReceivingActivityLocation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RequestingOfficeCaseNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("TemporaryIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EvidenceRoomId", "TemporaryIdentifier")
                        .IsUnique();

                    b.ToTable("EvidenceVouchers", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Cases.OfficialDocumentNumberAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AttestedAssignedInAuthoritativeLedger")
                        .HasColumnType("bit");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("EnteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EnteredByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SupersededByAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("SupersessionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TwoDigitYear")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId")
                        .IsUnique()
                        .HasDatabaseName("UX_DocumentNumber_OneCurrentPerVoucher")
                        .HasFilter("SupersededByAssignmentId IS NULL");

                    b.HasIndex("EvidenceRoomId", "CalendarYear", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_DocumentNumber_PerRoomPerYear")
                        .HasFilter("SupersededByAssignmentId IS NULL");

                    b.ToTable("OfficialDocumentNumberAssignments", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Configuration.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActingUserId")
                        .HasColumnType("int");

                    b.Property<string>("ActingUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AffectedRecordId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AffectedRecordType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ActingUserId", "OccurredAtUtc");

                    b.HasIndex("AffectedRecordType", "AffectedRecordId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Configuration.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccreditedClassificationLevel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AuthoritativeMode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AutomatedSystemApprovalDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AutomatedSystemApprovalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LocalSuspenseReviewThresholdDays")
                        .HasColumnType("int");

                    b.Property<int>("NumberingMode")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountableMailNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IdentificationVerified")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationOrAgency")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleOrGrade")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustodyParties", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Events.ItemEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("EvidenceItemId")
                        .HasColumnType("int");

                    b.Property<int>("HashSchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("OccurredAtLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("OccurredAtOffset")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreviousEventHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("SupersededByEventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupersededByEventId");

                    b.HasIndex("EvidenceItemId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ItemEvents_ItemSequence");

                    b.HasIndex("EvidenceItemId", "OccurredAtUtc", "SequenceNumber")
                        .HasDatabaseName("IX_ItemEvents_ItemChronology");

                    b.ToTable("ItemEvents", (string)null);

                    b.HasDiscriminator<string>("EventKind").HasValue("ItemEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Emc.Domain.Identity.CustodianAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppointingAuthority")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AppointmentOrderReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EligibilityAttested")
                        .HasColumnType("bit");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SupersededByAppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("SupersedesAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EvidenceRoomId", "AppointmentType")
                        .IsUnique()
                        .HasDatabaseName("UX_CustodianAppointments_OneOpenPerType")
                        .HasFilter("EffectiveTo IS NULL AND SupersededByAppointmentId IS NULL");

                    b.HasIndex("EvidenceRoomId", "UserId", "EffectiveFrom");

                    b.ToTable("CustodianAppointments", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDirectorySid")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("nvarchar(184)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationOrUnit")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RankOrGrade")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDirectorySid")
                        .IsUnique();

                    b.HasIndex("UserPrincipalName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Identity.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Storage.EvidenceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrganizationOrUnit")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EvidenceRooms", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Storage.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvidenceRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("EvidenceRoomId", "ParentId", "Name")
                        .IsUnique()
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("Emc.Domain.Events.CorrectionEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<string>("CorrectedValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("CorrectsEventId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MfrReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("SupervisorNotifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SupervisorNotifiedUserId")
                        .HasColumnType("int");

                    b.HasIndex("CorrectsEventId");

                    b.HasDiscriminator().HasValue("Correction");
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<string>("Agency")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Destination")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsScrcni")
                        .HasColumnType("bit");

                    b.Property<string>("PurposeOfChangeOfCustody")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReceivedByPartyId")
                        .HasColumnType("int");

                    b.Property<int>("ReleasedByPartyId")
                        .HasColumnType("int");

                    b.HasIndex("ReceivedByPartyId");

                    b.HasIndex("ReleasedByPartyId");

                    b.HasDiscriminator().HasValue("Custody");
                });

            modelBuilder.Entity("Emc.Domain.Events.DocumentNumberEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<bool>("AttestedAssignedInAuthoritativeLedger")
                        .HasColumnType("bit");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PreviousDocumentNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasDiscriminator().HasValue("DocumentNumber");
                });

            modelBuilder.Entity("Emc.Domain.Events.ExaminationEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<string>("ExaminationRequestReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExhibitNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExtractionDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Laboratory")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResultReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasDiscriminator().HasValue("Examination");
                });

            modelBuilder.Entity("Emc.Domain.Events.LocationEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StorageLocationId")
                        .HasColumnType("int");

                    b.Property<string>("StorageLocationPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.ToTable("ItemEvents", t =>
                        {
                            t.Property("Reason")
                                .HasColumnName("LocationEvent_Reason");
                        });

                    b.HasDiscriminator().HasValue("Location");
                });

            modelBuilder.Entity("Emc.Domain.Events.SealEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("DirectingSupervisorName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MfrReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PurposeOfBreach")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.ToTable("ItemEvents", t =>
                        {
                            t.Property("MfrReference")
                                .HasColumnName("SealEvent_MfrReference");
                        });

                    b.HasDiscriminator().HasValue("Seal");
                });

            modelBuilder.Entity("Emc.Domain.Events.StatusEvent", b =>
                {
                    b.HasBaseType("Emc.Domain.Events.ItemEvent");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.ToTable("ItemEvents", t =>
                        {
                            t.Property("Reason")
                                .HasColumnName("StatusEvent_Reason");
                        });

                    b.HasDiscriminator().HasValue("Status");
                });

            modelBuilder.Entity("Emc.Domain.Cases.Case", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceItem", b =>
                {
                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", "Voucher")
                        .WithMany("Items")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceVoucher", b =>
                {
                    b.HasOne("Emc.Domain.Cases.Case", "Case")
                        .WithMany("Vouchers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Emc.Domain.Cases.OfficialDocumentNumberAssignment", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Cases.EvidenceVoucher", "Voucher")
                        .WithMany("DocumentNumberAssignments")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyParty", b =>
                {
                    b.HasOne("Emc.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emc.Domain.Events.ItemEvent", b =>
                {
                    b.HasOne("Emc.Domain.Cases.EvidenceItem", null)
                        .WithMany("Events")
                        .HasForeignKey("EvidenceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Events.ItemEvent", null)
                        .WithMany()
                        .HasForeignKey("SupersededByEventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Emc.Domain.Identity.CustodianAppointment", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", null)
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emc.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("Emc.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emc.Domain.Storage.StorageLocation", b =>
                {
                    b.HasOne("Emc.Domain.Storage.EvidenceRoom", "EvidenceRoom")
                        .WithMany()
                        .HasForeignKey("EvidenceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Storage.StorageLocation", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EvidenceRoom");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Emc.Domain.Events.CorrectionEvent", b =>
                {
                    b.HasOne("Emc.Domain.Events.ItemEvent", "CorrectedEvent")
                        .WithMany()
                        .HasForeignKey("CorrectsEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorrectedEvent");
                });

            modelBuilder.Entity("Emc.Domain.Events.CustodyEvent", b =>
                {
                    b.HasOne("Emc.Domain.Events.CustodyParty", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Emc.Domain.Events.CustodyParty", "ReleasedBy")
                        .WithMany()
                        .HasForeignKey("ReleasedByPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivedBy");

                    b.Navigation("ReleasedBy");
                });

            modelBuilder.Entity("Emc.Domain.Cases.Case", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceItem", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Emc.Domain.Cases.EvidenceVoucher", b =>
                {
                    b.Navigation("DocumentNumberAssignments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Emc.Domain.Identity.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
