namespace Emc.Application.Documents;

/// <summary>What the store produced for one blob: a generated key, and the hash and length of exactly what it holds.</summary>
public sealed record StoredBlob(string StorageKey, string Sha256, long Length);

/// <summary>
/// Immutable binary storage for source documents and their rendered pages.
///
/// Keys are GENERATED by the store and contain nothing the uploader chose (DOC-006). Writes are
/// atomic: a blob is either wholly present under its key or absent. Reads and hash checks are by
/// key only. There is no overwrite; <see cref="TryDeleteAsync"/> exists solely so a failed
/// database write can remove the blob it would have referenced.
///
/// Domain and application code never see a path. The filesystem implementation lives in
/// infrastructure, outside the web root, with documented ACL expectations.
/// </summary>
public interface ISourceDocumentStore
{
    /// <summary>Stores the stream's bytes under a new key. Hashes what was actually written.</summary>
    Task<StoredBlob> WriteAsync(string category, Stream content, CancellationToken ct = default);

    /// <summary>The blob's bytes, or null when the key holds nothing.</summary>
    Task<Stream?> OpenReadAsync(string storageKey, CancellationToken ct = default);

    /// <summary>The SHA-256 of the bytes currently stored under the key, or null when missing.</summary>
    Task<string?> ComputeSha256Async(string storageKey, CancellationToken ct = default);

    /// <summary>Removes a blob that no record references. Returns false when nothing was there.</summary>
    Task<bool> TryDeleteAsync(string storageKey, CancellationToken ct = default);

    /// <summary>Every blob the store holds, with its state (committed, or a partial left by an interrupted write) and last write time. For the orphan sweep only.</summary>
    Task<IReadOnlyList<StoredBlobEntry>> EnumerateAsync(CancellationToken ct = default);

    /// <summary>Removes a partial file left by an interrupted write. Returns false when nothing was there.</summary>
    Task<bool> TryDeletePartialAsync(string storageKey, CancellationToken ct = default);
}

public enum StoredBlobState
{
    /// <summary>Wholly present under its key. Referenced or not is the database's knowledge, not the store's.</summary>
    Committed = 1,

    /// <summary>A ".partial" left by a write that did not complete. Never referenced by any record.</summary>
    Partial = 2
}

/// <summary>One entry of the store, for the orphan sweep: the key, its state, and when it was last written.</summary>
public sealed record StoredBlobEntry(string StorageKey, StoredBlobState State, DateTimeOffset LastWriteUtc, long Length);

public sealed record PdfPageDimensions(int PageNumber, double WidthPoints, double HeightPoints);

public sealed record RenderedPage(int PageNumber, int WidthPx, int HeightPx, int Dpi, byte[] Png);

/// <summary>
/// Rasterizes PDF pages to PNG. The PDF is HOSTILE INPUT: the implementation must apply the
/// page-count, dimension and pixel limits it is given, never follow a URL, never load a remote
/// font, and never execute embedded content. Nothing about the document's text reaches a log.
/// </summary>
public interface IPdfRasterizer
{
    /// <summary>Identifies the engine and version used, recorded on every rendered page.</summary>
    string RendererVersion { get; }

    /// <summary>Page count, or throws <see cref="MalformedPdfException"/> if the bytes cannot be opened as a PDF.</summary>
    int GetPageCount(byte[] pdf);

    IReadOnlyList<PdfPageDimensions> GetPageDimensions(byte[] pdf);

    RenderedPage Render(byte[] pdf, int pageNumber, int dpi, CancellationToken ct = default);
}

/// <summary>The bytes could not be interpreted as a PDF. Carries no document content.</summary>
public sealed class MalformedPdfException : Exception
{
    public MalformedPdfException(string message, Exception? inner = null) : base(message, inner) { }
}

/// <summary>The rendering process died, was killed on timeout, or produced no usable output. Carries no document content.</summary>
public sealed class RendererCrashedException : Exception
{
    public RendererCrashedException(string message, Exception? inner = null) : base(message, inner) { }
}

/// <summary>Limits and locations. Bound from configuration; every limit is enforced in code as well as at the framework.</summary>
public sealed class SourceDocumentOptions
{
    public const string SectionName = "SourceDocuments";

    /// <summary>Filesystem root for the store. Must be OUTSIDE the web root; see docs/architecture.md §9.</summary>
    public string RootPath { get; set; } = string.Empty;

    /// <summary>Largest accepted upload. Also applied at the request layer (Program.cs, upload page).</summary>
    public long MaxContentBytes { get; set; } = 50L * 1024 * 1024;

    public int MaxPageCount { get; set; } = 200;

    /// <summary>Largest page, in pixels at the render DPI. Letter at 150 DPI is about 2.1 million.</summary>
    public long MaxPixelsPerPage { get; set; } = 30_000_000;

    public int RenderDpi { get; set; } = 150;

    /// <summary>Hard timeout per page. In the worker this kills the rendering child process; it is a real timeout (DOC-014).</summary>
    public int RenderTimeoutSeconds { get; set; } = 60;

    /// <summary>Path to the rendering helper executable (the worker itself, run in "render" mode). Empty means render in-process (tests only).</summary>
    public string RenderHelperPath { get; set; } = string.Empty;

    /// <summary>Private working folder for the render helper's per-invocation files.</summary>
    public string RenderWorkRoot { get; set; } = string.Empty;

    public int RenderLeaseSeconds { get; set; } = 900;
    public int MaxRenderAttempts { get; set; } = Emc.Domain.Documents.DocumentRenderJob.DefaultMaxAttempts;

    /// <summary>The same bytes, by the same user, for the same voucher, within this window is a repeated request, not a second document (DOC-010).</summary>
    public int DuplicateRequestWindowSeconds { get; set; } = 120;
}
